[project]
name = "vita"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Víctor Manuel Chaves García", email = "victormcg96@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "typer>=0.27.1",
]

[project.scripts]
vita = "vita.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
